import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          If you can dream it,
          <br />
          You can do it
          <br />- my todo -
        </div>
        <nav>
          <Link href="/about">ABOUT</Link>
          <Link href="/todos-csr">TODOS-CSR</Link>
          <Link href="/todos-ssr">TODOS-SSR</Link>
          <Link href="/report">REPORT</Link>
        </nav>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
